### ISSUE TITLE
Issue running code with Rbbg from batch file

### ISSUE THREAD

**Issue by billelev** [johnlaing/blpwrapper#3]
I am having an issue running R code from a batch file, executed via Windows Scheduler, but only sometimes.  The code always runs if I run the code directly from the batch file, or from an R command prompt.

This is the error message I get, and it requests I report it to the blpwrapper maintainer...I think I am in the right place...

```
R version 3.2.1 (2015-06-18) 
rJava Version 0.9-8 
Rbbg Version 0.5.3 
Java environment initialized successfully.
Looking for most recent blpapi3.jar file...
Adding C:\blp\API\APIv3\JavaAPI\v3.7.1.1\lib\blpapi3.jar to Java classpath
Bloomberg API Version 3.7.1.1 

Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  org.findata.blpwrapper.WrapperException: Session not started. See logs. Please report this to blpwrapper maintainer.
Calls: GetSignal ... <Anonymous> -> .jrcall -> .jcall -> .jcheck -> .Call
Execution halted
```

The line in the batch file is as follows

`R CMD BATCH "C:\Users\joe\repos\equity-signals\run\signals_exec.R" "C:\Batch Files\signals_summary.R"
`

Any help as to why this occurring would be appreciated.

**Comment by danielkrizian** [comment]
@billelev I believe https://github.com/Rblp/Rblpapi is a successor package, actively maintained, better, without Java dependency.
Genealogy here: http://dirk.eddelbuettel.com/papers/rfinance2015_may2015_rblpapi.pdf

**Comment by billelev** [comment]
@danielkrizian Ahh...great.  I had missed the new package.  Given it does not utilize Java, and my issues are with Java, hopefully all will be well.  Thanks for your prompt.

**Comment by johnlaing** [comment]
@danielkrizian is correct in all the benefits of Rblpapi.

@billelev - I can still help you try to fix issues you may have with Rbbg. However, you've given me very little information with which to do that. For example, what's in your R scripts? Do they work when sourced from an interactive console?

**Comment by billelev** [comment]
@johnlaing it might be easiest for me to switch to Rblpapi and see if I still encounter issues.

It's difficult for me to provide a full working example because the code is in multiple files, loops through many functions/securities, and only fails sometimes.  

What is certain is that 
- it always runs from an R session/console e.g. command prompt or RStudio
- it always runs when I manually start the script from a batch file
- it _sometimes_ fails when the script is called from a batch file via Windows Scheduler

i.e. I only ran in to problems once I attempted to automate the script in nightly runs.

Here is an example of what I'm doing:

I have many "signals" that are self contained R scripts.  e.g. a signal may be called 'spxfe', that code resides in spxfe.R and the ticker for the data relating to the signal is 'spxfe'.

I have a list of tickers, I loop through each ticker, source the ticker.R script, call the GetSignal() function that is in each ticker.R file.  That GetSignal() function ultimately calls bdh().

e.g. this is the output file from the Windows Scheduler batch run.

```
R version 3.2.1 (2015-06-18) -- "World-Famous Astronaut"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: i386-w64-mingw32/i386 (32-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> 
> # Clear variables
> rm(list=setdiff(ls(), c("source.vp", "SourceAllFiles")))
> 
> source.vp("vp")
data_aws_connect.R :Loading required package: RPostgreSQL
Loading required package: DBI

data_aws_query.R :Loading required package: reshape

data_bbg.R :Loading required package: Rbbg
Loading required package: rJava
Loading required package: lubridate

Attaching package: 'lubridate'

The following object is masked from 'package:reshape':

    stamp


data_csv.R :
data_quandl.R :Loading required package: Quandl
Loading required package: xts
Loading required package: zoo

Attaching package: 'zoo'

The following objects are masked from 'package:base':

    as.Date, as.Date.numeric


data_quantmod.R :Loading required package: quantmod
Loading required package: TTR
Version 0.4-0 included new data defaults. See ?getSymbols.

data_utility_functions.R :
date_utility_functions.R :
file_utility_functions.R :
slack.r :
ts_utility_functions.R :
Warning messages:
1: package 'reshape' was built under R version 3.2.3 
2: package 'rJava' was built under R version 3.2.3 
3: package 'Quandl' was built under R version 3.2.2 
4: package 'zoo' was built under R version 3.2.2 
5: package 'quantmod' was built under R version 3.2.2 
6: package 'TTR' was built under R version 3.2.2 
> source.vp("equity-signals")
equity-signals.R :Loading required package: gridExtra

Warning message:
package 'gridExtra' was built under R version 3.2.3 
> 
> InitSlackr(channel = "#signals", bTestMode = FALSE)
> 
> 
> # This initial list of tickers have no depencies
> tickers_l0 <- c("aaii","cyclicals","putcalloex","spxfe","volsig","cx13w26w","inverse",
+                 "ecosurprise","realizedvol","vixmacd","vixinversion","breadthnyse",
+                 "sellpress","sellexh","nanyvol","arms")
> 
> # This second set of tickers have successive dependencies.
> #  l2 depend on some of l1, l3 depends on some of l2
> tickers_l1 <- c("defcyc","mc4w8w","nysemargin")
> tickers_l2 <- c("gcstress",  # Depends on defcyc
+                 "inflpress"  # Depends on mc4w8w
+                 )  
> tickers_l3 <- c("crash","crash_strong")  # Depend on gcstress
> tickers_l4 <- c("vixbuy",  # Depend on crash
+                 "stocksbonds",  # Depend on crash and nysemargin
+                 "mcclellan","putcall","putcallv",  # Depend on crash_strong
+                 "volume"  # Depend on crash_strong and mc4w8w
+                 )
> 
> tickers <- list(tickers_l0, tickers_l1, tickers_l2, tickers_l3, tickers_l4)
> 
> # Run through all signals and update database
> for (i in 1:length(tickers)) {
+   
+   ticker <- tickers[[i]]
+   for (j in 1:length(ticker)) {
+ 
+     fPath <- file.path("equity-signals", "signal_scripts", paste0(ticker[j], ".R"))
+     source(fPath)
+ 
+     if (vpp(ticker[j])$type == "signal") {
+       signal <- GetSignal()
+       InsertSignal(ticker[j], signal)
+     } else {
+       index <- GetIndex()
+       InsertIndex(ticker[j], index)
+     }
+ 
+   }
+   
+ }
R version 3.2.1 (2015-06-18) 
rJava Version 0.9-8 
Rbbg Version 0.5.3 
Java environment initialized successfully.
Looking for most recent blpapi3.jar file...
Adding C:\blp\API\APIv3\JavaAPI\v3.7.1.1\lib\blpapi3.jar to Java classpath
Bloomberg API Version 3.7.1.1 
Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  org.findata.blpwrapper.WrapperException: Session not started. See logs. Please report this to blpwrapper maintainer.
Calls: GetSignal ... <Anonymous> -> .jrcall -> .jcall -> .jcheck -> .Call
Execution halted
```

**Comment by johnlaing** [comment]
If, as you say:
- it always runs from an R session/console e.g. command prompt or RStudio
- it always runs when I manually start the script from a batch file
- it sometimes fails when the script is called from a batch file via Windows Scheduler

Then it's unlikely that your problem is with the package itself. One possibility is that your Bloomberg connection has been terminated by the time your automated job runs. This could also explain the sporadic nature of the failures you're seeing.

As the error message says: See logs. There should be a file that looks like `org.findata.blpwrapper*`. Check if there's anything useful in there.

**Comment by billelev** [comment]
I have updated my code to use Rblpapi, but to close this out, the only thing that I can think was causing the issue was that sometimes, due to scheduling, two batch files would be running at the same time.  Maybe the creation of the second R instance making Bloombeg calls made the first fail (sometimes).
